name: Build LK for MT6580

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update -y
        sudo apt-get install -y git

    - name: Clone GCC toolchain repository
      run: git clone https://github.com/Skyrimus/arm-eabi-4.8-google-mt6580 gcc

    - name: Navigate to main directory
      run: cd ..

    - name: Clone LK repository
      run: git clone https://github.com/Ultimate-1/lk_mt6580.git
      working-directory: lk_mt6580

    - name: Set up environment variables
      run: |
        export TOOLCHAIN_PREFIX=${PWD}/gcc/bin/arm-eabi-

    - name: Build LK for MT6580
      run: make hexing6580_weg_l
