name: Build LK for Hexing6580_WEG_L

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git

        # Clone the GCC toolchain repository if not already present
        [ -d "gcc" ] || git clone https://github.com/Skyrimus/arm-eabi-4.8-google-mt6580 gcc

        # Navigate back to the main directory
        cd ..

        # Clone the LK (Little Kernel) repository if not already present
        [ -d "lk_mt6580" ] || git clone https://github.com/Ultimate-1/lk_mt6580.git
        cd lk_mt6580

        # Set up environment variables
        export TOOLCHAIN_PREFIX=${PWD}/../gcc/bin/arm-eabi-
        echo "export PATH=\$PATH:${TOOLCHAIN_PREFIX}" >> $GITHUB_ENV

    - name: Build LK
      run: |
        make hexing6580_weg_l
