#!/bin/bash

# Clone the GCC toolchain repository
git clone https://github.com/Skyrimus/arm-eabi-4.8-google-mt6580 gcc

# Navigate back to the main directory
cd ..

# Clone the LK (Little Kernel) repository
git clone https://github.com/Ultimate-1/lk_mt6580.git
cd lk_mt6580

# Set up environment variables
export TOOLCHAIN_PREFIX=${PWD}/../gcc/bin/arm-eabi-

# Build LK for your target
make hexing6580_weg_l
