name: Build LK for Hexing6580_WEG_L

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git

        # Clone the GCC toolchain repository if not already present
        [ -d "gcc" ] || git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 gcc

        # Add the toolchain to PATH
        echo "export PATH=\$PATH:${PWD}/gcc/bin" >> $GITHUB_ENV

        # Navigate back to the main directory
        cd ..

        # Clone the LK (Little Kernel) repository if not already present
        [ -d "lk_mt6580" ] || git clone https://github.com/Ultimate-1/lk_mt6580.git
        cd lk_mt6580

    - name: Build LK
      run: |
        export TOOLCHAIN_PREFIX=${PWD}/gcc/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-
        make hexing6580_weg_l
